### ISSUE TITLE
netbox-2.7

### ISSUE THREAD

**Issue by ThomasADavis** [Solvik/netbox_agent#102]
Working with the beta, the interfaces types changed..  So that is some that needs to be fixed.  Not sure what else is broken.

**Comment by ThomasADavis** [comment]
Use nb.dcim.choices() api to fix this..

all constants can then be looked up from the API.

**Comment by Solvik** [comment]
I've tried to do extensive tests since the docker image of 2.7 is available (https://github.com/netbox-community/netbox-docker/releases/tag/0.21.0)

I've upgraded pynetbox to the latest version and tested if with your PR #107 and all seems well
We're gonna be able to release a netbox 2.7 compatible agent thanks to you!
